# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ME 6402
email: mtucker@gatech.edu
description: >- # this means to ignore newlines until "baseurl:"
  Course website for Georgia Tech course ME 6402: Nonlinear Control Systems
baseurl: "/ME6402" # the subpath of your site, e.g. /blog
url: "https://maegant.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  maegant

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

# Collections for website data
collections:
  modules:
    output: true
  notebooks:
    output: true
    permalink: code/:path/
    
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      type: notebooks
    values:
      layout: pynotebook

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
